version: '3.9' # Versi칩n del esquema de Docker Compose

services:
  react-app:
    build:
      context: . # El directorio donde se encuentra el Dockerfile
      dockerfile: axislogin/Dockerfile
    ports:
      - "8080:80" # Mapea el puerto 80 del contenedor al 8080 de tu m치quina
    volumes:
      - ./build:/usr/share/nginx/html # (Opcional) Sincronizaci칩n de archivos
    restart: always # Reinicia el contenedor autom치ticamente si falla
    